-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 12:48:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ejemplo_producto` ;

-- -----------------------------------------------------
-- Schema ejemplo_producto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejemplo_producto` ;
USE `ejemplo_producto` ;

-- -----------------------------------------------------
-- Table `ejemplo_producto`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`CLIENTE` (
  `DNI` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `APELLIDOS` VARCHAR(20) NOT NULL,
  `FECHA_NAC` DATE NOT NULL,
  `TLFN` VARCHAR(11) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PROVEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PROVEDOR` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PROVEDOR` (
  `NIF` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `DIRECCION` TEXT(60) NOT NULL,
  PRIMARY KEY (`NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`PRODUCTO` (
  `CODIGO` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL DEFAULT '\"ninguno\"',
  `PRECIO` FLOAT NOT NULL DEFAULT 0.0,
  `PROVEDOR_NIF` INT NOT NULL,
  PRIMARY KEY (`CODIGO`),
  INDEX `fk_PRODUCTO_PROVEDOR1_idx` (`PROVEDOR_NIF` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_PROVEDOR1`
    FOREIGN KEY (`PROVEDOR_NIF`)
    REFERENCES `ejemplo_producto`.`PROVEDOR` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejemplo_producto`.`COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ejemplo_producto`.`COMPRA` ;

CREATE TABLE IF NOT EXISTS `ejemplo_producto`.`COMPRA` (
  `CLIENTE_DNI` INT NOT NULL,
  `PRODUCTO_CODIGO` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_DNI`, `PRODUCTO_CODIGO`),
  INDEX `fk_CLIENTE_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_CODIGO` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_PRODUCTO_CLIENTE_idx` (`CLIENTE_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_CLIENTE`
    FOREIGN KEY (`CLIENTE_DNI`)
    REFERENCES `ejemplo_producto`.`CLIENTE` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_CODIGO`)
    REFERENCES `ejemplo_producto`.`PRODUCTO` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
